# Adds ~/Source/Scripts to the top of PATH (if it exists):
if [ -d "${HOME}/Source/Scripts" ]; then
  export PATH="${HOME}/Source/Scripts:${PATH}"
fi

# Adds ~/.local/bin to the top of PATH (if it exists):
if [ -d "${HOME}/.local/bin" ]; then
  export PATH="${HOME}/.local/bin:${PATH}"
fi

# Includes .bashrc (if it exists)
if [ -f "${HOME}/.bashrc" ]; then
  . "${HOME}/.bashrc"
fi
